# Generated by Django 3.1.1 on 2020-10-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='session',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
