# Generated by Django 2.0.2 on 2021-04-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0002_auto_20210420_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
