# Generated by Django 3.1.1 on 2020-11-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0002_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='learning_system_app.categoryname'),
            preserve_default=False,
        ),
    ]
