# Generated by Django 3.1.1 on 2020-11-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0003_auto_20201101_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='display_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
