# Generated by Django 2.0.2 on 2021-04-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0003_user_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='last_redeem_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
