# Generated by Django 3.1.1 on 2020-10-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0004_user_profile_image_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image_qr',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
