# Generated by Django 3.1.1 on 2020-10-13 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_system_app', '0005_auto_20201013_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='')),
                ('image_qr', models.ImageField(blank=True, upload_to='')),
                ('dob', models.DateField()),
                ('address', models.TextField(max_length=500)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('qualifications', models.CharField(max_length=500)),
                ('year_of_experience', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('special_price', models.FloatField()),
                ('description', models.TextField(max_length=1000)),
                ('mini_info', models.TextField(blank=True, max_length=400, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('prequisites', models.CharField(max_length=50)),
                ('has_certificate', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system_app.instructor')),
            ],
        ),
    ]
