# Generated by Django 3.1.1 on 2020-11-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0005_auto_20201102_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='intro_video',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
