# Generated by Django 3.1.1 on 2020-11-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0007_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
