# Generated by Django 3.1.1 on 2020-10-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0007_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
