# Generated by Django 3.1.1 on 2020-11-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0008_course_price_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
