# Generated by Django 3.1.1 on 2020-11-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0009_enrolledcourse_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
