# Generated by Django 3.1.1 on 2020-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0010_course_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='request_deactivate',
            field=models.IntegerField(default=1),
        ),
    ]
