# Generated by Django 3.1.1 on 2020-11-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0011_enrolledcourse_request_deactivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
