# Generated by Django 3.1.1 on 2020-11-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0012_enrolledcourse_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
