# Generated by Django 3.1.1 on 2020-10-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0015_auto_20201014_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
