# Generated by Django 3.1.1 on 2020-10-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0017_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='resources',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
