# Generated by Django 3.1.1 on 2020-10-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0022_review_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_question', to='learning_system_app.course'),
        ),
    ]
