# Generated by Django 3.1.1 on 2020-10-18 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0024_auto_20201018_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_question', to='learning_system_app.subject'),
        ),
    ]
