# Generated by Django 3.1.1 on 2020-10-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0029_studymaterial_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
